/**
 * Authentication Context
 * Provides global Firebase Auth state management
 * v0.5.14 - SRS_DB.md compliant with username selection dialog
 */

import { createContext, useContext, useEffect, useState, type ReactNode } from 'react';
import type { User as FirebaseUser } from 'firebase/auth';
import {
  signInWithEmail,
  signUpWithEmailAndCreateProfile,
  signInWithGoogle,
  signOutUser,
  onAuthStateChange,
  ensureUserProfile,
} from '../services/auth';
import { getUser } from '../services/firestore';
import { logger } from '../utils/logger';
import { UsernameSelectionDialog } from '../components/UsernameSelectionDialog';
import type { User } from '../types';

interface AuthContextType {
  user: FirebaseUser | null;
  userProfile: User | null;
  loading: boolean;
  signIn: (email: string, password: string) => Promise<void>;
  signUp: (email: string, password: string, username: string, displayName?: string) => Promise<void>;
  signInWithGoogleOAuth: () => Promise<void>;
  signOut: () => Promise<void>;
  refreshUserProfile: () => Promise<void>;
}

const AuthContext = createContext<AuthContextType | undefined>(undefined);

interface AuthProviderProps {
  children: ReactNode;
}

/**
 * Check if a username appears to be auto-generated
 * Auto-generated usernames are either:
 * - First part of email (before @)
 * - First 8 characters of Firebase UID
 */
function isAutoGeneratedUsername(username: string, email: string | null, uid: string): boolean {
  if (!username) return true;

  // Check if username is first part of email
  if (email) {
    const emailPrefix = email.split('@')[0]?.toLowerCase();
    if (username === emailPrefix) return true;
  }

  // Check if username is first 8 chars of UID
  if (username === uid.slice(0, 8)) return true;

  return false;
}

export function AuthProvider({ children }: AuthProviderProps) {
  const [user, setUser] = useState<FirebaseUser | null>(null);
  const [userProfile, setUserProfile] = useState<User | null>(null);
  const [loading, setLoading] = useState(true);
  const [showUsernameDialog, setShowUsernameDialog] = useState(false);

  // Load user profile from Firestore
  const loadUserProfile = async (firebaseUser: FirebaseUser): Promise<User | null> => {
    try {
      const profile = await getUser(firebaseUser.uid);
      setUserProfile(profile);
      return profile;
    } catch (error) {
      logger.warn('Failed to load user profile', { error, uid: firebaseUser.uid });
      return null;
    }
  };

  // Refresh user profile (call after username update)
  const refreshUserProfile = async () => {
    if (user) {
      await loadUserProfile(user);
    }
  };

  useEffect(() => {
    // Subscribe to Firebase Auth state changes
    const unsubscribe = onAuthStateChange(async (firebaseUser) => {
      setUser(firebaseUser);

      if (firebaseUser) {
        // Ensure user has a Firestore profile (for session restore and legacy users)
        try {
          await ensureUserProfile(firebaseUser);
        } catch (error) {
          logger.warn('Failed to ensure user profile', { error, uid: firebaseUser.uid });
        }

        // Load the user profile
        const profile = await loadUserProfile(firebaseUser);

        // Check if user needs to select a username (auto-generated)
        if (profile && isAutoGeneratedUsername(profile.username, firebaseUser.email, firebaseUser.uid)) {
          setShowUsernameDialog(true);
        }

        logger.info('User authenticated', {
          uid: firebaseUser.uid,
          email: firebaseUser.email
        });
      } else {
        setUserProfile(null);
        setShowUsernameDialog(false);
        logger.info('User signed out');
      }

      setLoading(false);
    });

    return () => unsubscribe();
  }, []);

  const handleSignIn = async (email: string, password: string) => {
    try {
      await signInWithEmail(email, password);
      logger.info('Sign in successful', { email });
    } catch (error) {
      logger.error('Sign in failed', { error });
      throw error;
    }
  };

  const handleSignUp = async (
    email: string,
    password: string,
    username: string,
    displayName?: string
  ) => {
    try {
      await signUpWithEmailAndCreateProfile(email, password, username, displayName);
      logger.info('Sign up successful', { email, username });
    } catch (error) {
      logger.error('Sign up failed', { error });
      throw error;
    }
  };

  const handleGoogleSignIn = async () => {
    try {
      await signInWithGoogle();
      logger.info('Google sign in successful');
    } catch (error) {
      logger.error('Google sign in failed', { error });
      throw error;
    }
  };

  const handleSignOut = async () => {
    try {
      await signOutUser();
      logger.info('Sign out successful');
    } catch (error) {
      logger.error('Sign out failed', { error });
      throw error;
    }
  };

  // Handle successful username selection
  const handleUsernameSuccess = async (username: string) => {
    setShowUsernameDialog(false);
    // Refresh user profile to get the updated username
    await refreshUserProfile();
    logger.info('Username selected', { username });
  };

  const value: AuthContextType = {
    user,
    userProfile,
    loading,
    signIn: handleSignIn,
    signUp: handleSignUp,
    signInWithGoogleOAuth: handleGoogleSignIn,
    signOut: handleSignOut,
    refreshUserProfile,
  };

  return (
    <AuthContext.Provider value={value}>
      {children}
      {/* Username selection dialog for new users with auto-generated usernames */}
      {user && showUsernameDialog && (
        <UsernameSelectionDialog
          open={showUsernameDialog}
          userId={user.uid}
          suggestedUsername={userProfile?.username || ''}
          onSuccess={handleUsernameSuccess}
          // No onClose - dialog is mandatory for new users
        />
      )}
    </AuthContext.Provider>
  );
}

/**
 * Custom hook to access auth context
 * Throws error if used outside AuthProvider
 */
export function useAuth(): AuthContextType {
  const context = useContext(AuthContext);
  if (context === undefined) {
    throw new Error('useAuth must be used within an AuthProvider');
  }
  return context;
}
