/**
 * ImportTimelineDialog - Dialog for importing timelines from YAML files
 * Implements CC-REQ-IMPORT-001 through CC-REQ-IMPORT-005 (v0.5.27)
 *
 * Features:
 * - File upload via drag-and-drop or file picker
 * - YAML validation with detailed error messages
 * - Preview of timeline metadata and events before import
 * - Auto-generated timeline ID from title
 */

import { useState, useCallback, useRef, useMemo, useEffect } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  Alert,
  Box,
  Typography,
  Chip,
  Paper,
  List,
  ListItem,
  ListItemText,
  Divider,
  TextField,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  CircularProgress,
} from '@mui/material';
import { createTimeline, isTimelineIdUnique, getUser } from '../services/firestore';
import { generateSlugFromTitle } from '../lib/homePageStorage';
import { useAuth } from '../contexts/AuthContext';
import { importTimelineFromYaml, type ImportResult, type ValidationError } from '../services/timelineImportExport';
import type { TimelineVisibility, User } from '../types';

interface ImportTimelineDialogProps {
  open: boolean;
  onClose: () => void;
  onSuccess: (timelineId: string) => void;
}

type ImportStep = 'upload' | 'preview' | 'creating';

export function ImportTimelineDialog({ open, onClose, onSuccess }: ImportTimelineDialogProps) {
  const { user: firebaseUser } = useAuth();
  const currentUserId = firebaseUser?.uid;
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [currentUser, setCurrentUser] = useState<User | null>(null);

  // Load current user profile from Firestore
  useEffect(() => {
    async function loadUser() {
      if (firebaseUser) {
        const userProfile = await getUser(firebaseUser.uid);
        setCurrentUser(userProfile);
      } else {
        setCurrentUser(null);
      }
    }
    loadUser();
  }, [firebaseUser]);

  // Import state
  const [step, setStep] = useState<ImportStep>('upload');
  const [isDragging, setIsDragging] = useState(false);
  const [importResult, setImportResult] = useState<ImportResult | null>(null);
  const [validationErrors, setValidationErrors] = useState<ValidationError[]>([]);
  const [generalError, setGeneralError] = useState('');
  const [pastedYaml, setPastedYaml] = useState('');

  // Editable fields (can override imported values)
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [customId, setCustomId] = useState('');
  const [isIdManuallyEdited, setIsIdManuallyEdited] = useState(false);
  const [visibility, setVisibility] = useState<TimelineVisibility>('private');
  const [idError, setIdError] = useState('');

  // Auto-generate ID from title
  const autoGeneratedSlug = useMemo(() => {
    return title ? generateSlugFromTitle(title) : '';
  }, [title]);

  // Update customId when slug changes (if not manually edited)
  useEffect(() => {
    if (!isIdManuallyEdited) {
      setCustomId(autoGeneratedSlug);
    }
  }, [autoGeneratedSlug, isIdManuallyEdited]);

  // Validate custom ID
  const validateCustomId = async (value: string): Promise<string> => {
    if (!value) return 'Timeline ID is required';
    const validFormat = /^[a-z0-9-]+$/.test(value);
    if (!validFormat) {
      return 'ID must contain only lowercase letters, numbers, and hyphens';
    }
    if (currentUserId) {
      const fullId = `timeline-${value}`;
      const isUnique = await isTimelineIdUnique(fullId, currentUserId);
      if (!isUnique) {
        return 'This ID already exists for your account';
      }
    }
    return '';
  };

  const handleIdBlur = async () => {
    const error = await validateCustomId(customId);
    setIdError(error);
  };

  // Process YAML content (from file or paste)
  const processYamlContent = useCallback((content: string) => {
    setGeneralError('');
    setValidationErrors([]);

    try {
      const result = importTimelineFromYaml(content);

      if (!result.success || !result.result) {
        setValidationErrors(result.errors || []);
        return;
      }

      // Import successful - populate form
      setImportResult(result.result);
      setTitle(result.result.title);
      setDescription(result.result.description || '');
      setVisibility(result.result.visibility);
      setIsIdManuallyEdited(false);
      setPastedYaml('');
      setStep('preview');
    } catch (error) {
      setGeneralError(error instanceof Error ? error.message : 'Failed to parse YAML');
    }
  }, []);

  // Process uploaded file
  const processFile = useCallback(async (file: File) => {
    setGeneralError('');
    setValidationErrors([]);

    // Validate file type
    if (!file.name.endsWith('.yaml') && !file.name.endsWith('.yml')) {
      setGeneralError('Please upload a YAML file (.yaml or .yml)');
      return;
    }

    // Validate file size (max 1MB)
    if (file.size > 1024 * 1024) {
      setGeneralError('File too large. Maximum size is 1MB.');
      return;
    }

    try {
      const content = await file.text();
      processYamlContent(content);
    } catch (error) {
      setGeneralError(error instanceof Error ? error.message : 'Failed to read file');
    }
  }, [processYamlContent]);

  // Process pasted YAML
  const processPastedYaml = useCallback(() => {
    const content = pastedYaml.trim();
    if (!content) {
      setGeneralError('Please paste YAML content first');
      return;
    }

    // Validate size (max 1MB)
    if (content.length > 1024 * 1024) {
      setGeneralError('Content too large. Maximum size is 1MB.');
      return;
    }

    processYamlContent(content);
  }, [pastedYaml, processYamlContent]);

  // Drag and drop handlers
  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(true);
  }, []);

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
  }, []);

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    const file = e.dataTransfer.files[0];
    if (file) {
      processFile(file);
    }
  }, [processFile]);

  const handleFileSelect = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      processFile(file);
    }
  }, [processFile]);

  const handleBrowseClick = () => {
    fileInputRef.current?.click();
  };

  // Create timeline from imported data
  const handleCreate = async () => {
    if (!currentUserId || !importResult) {
      setGeneralError('You must be logged in to import a timeline');
      return;
    }

    // Validate ID
    const idValidationError = await validateCustomId(customId);
    if (idValidationError) {
      setIdError(idValidationError);
      return;
    }

    setStep('creating');
    setGeneralError('');

    try {
      const fullId = `timeline-${customId}`;

      const timelineId = await createTimeline(
        {
          title,
          description,
          ownerId: currentUserId,
          visibility,
          events: importResult.events,
          eventCount: importResult.events.length,
          viewCount: 0,
          featured: false,
        },
        fullId
      );

      handleClose();
      onSuccess(timelineId);
    } catch (error) {
      setStep('preview');
      setGeneralError(error instanceof Error ? error.message : 'Failed to create timeline');
    }
  };

  const handleClose = () => {
    // Reset all state
    setStep('upload');
    setIsDragging(false);
    setImportResult(null);
    setValidationErrors([]);
    setGeneralError('');
    setPastedYaml('');
    setTitle('');
    setDescription('');
    setCustomId('');
    setIsIdManuallyEdited(false);
    setVisibility('private');
    setIdError('');
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
    onClose();
  };

  const handleBack = () => {
    setStep('upload');
    setImportResult(null);
    setValidationErrors([]);
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  const isFormValid = title.length >= 3 && customId.length > 0 && !idError;

  return (
    <Dialog
      open={open}
      onClose={handleClose}
      maxWidth="sm"
      fullWidth
      PaperProps={{ sx: { minHeight: 400 } }}
    >
      <DialogTitle>
        {step === 'upload' && 'Import Timeline from YAML'}
        {step === 'preview' && 'Review Import'}
        {step === 'creating' && 'Creating Timeline...'}
      </DialogTitle>

      <DialogContent>
        {generalError && (
          <Alert severity="error" sx={{ mb: 2 }}>
            {generalError}
          </Alert>
        )}

        {/* Step 1: Upload */}
        {step === 'upload' && (
          <>
            {/* Validation errors */}
            {validationErrors.length > 0 && (
              <Alert severity="error" sx={{ mb: 2 }}>
                <Typography variant="subtitle2" sx={{ mb: 1 }}>
                  YAML validation failed:
                </Typography>
                <List dense sx={{ py: 0 }}>
                  {validationErrors.map((err, i) => (
                    <ListItem key={i} sx={{ py: 0, px: 0 }}>
                      <ListItemText
                        primary={`${err.field}: ${err.message}`}
                        primaryTypographyProps={{ variant: 'body2' }}
                      />
                    </ListItem>
                  ))}
                </List>
              </Alert>
            )}

            {/* Drop zone */}
            <Paper
              variant="outlined"
              onDragOver={handleDragOver}
              onDragLeave={handleDragLeave}
              onDrop={handleDrop}
              sx={{
                p: 4,
                textAlign: 'center',
                border: '2px dashed',
                borderColor: isDragging ? 'primary.main' : 'divider',
                backgroundColor: isDragging ? 'action.hover' : 'background.paper',
                cursor: 'pointer',
                transition: 'all 0.2s ease',
                '&:hover': {
                  borderColor: 'primary.main',
                  backgroundColor: 'action.hover',
                },
              }}
              onClick={handleBrowseClick}
            >
              <input
                ref={fileInputRef}
                type="file"
                accept=".yaml,.yml"
                onChange={handleFileSelect}
                style={{ display: 'none' }}
                data-testid="yaml-file-input"
              />
              <span className="material-symbols-rounded text-4xl text-gray-400 mb-2 block">
                upload_file
              </span>
              <Typography variant="body1" sx={{ mb: 1 }}>
                Drag and drop a YAML file here
              </Typography>
              <Typography variant="body2" color="text.secondary">
                or click to browse
              </Typography>
            </Paper>

            <Typography variant="caption" color="text.secondary" sx={{ mt: 2, display: 'block' }}>
              Accepts .yaml or .yml files up to 1MB. The file should follow the PowerTimeline YAML format.
            </Typography>

            <Divider sx={{ my: 2 }}>
              <Typography variant="caption" color="text.secondary">OR</Typography>
            </Divider>

            <TextField
              multiline
              rows={6}
              fullWidth
              placeholder="Paste YAML content here..."
              value={pastedYaml}
              onChange={(e) => setPastedYaml(e.target.value)}
              inputProps={{
                'data-testid': 'yaml-paste-input',
                style: { fontFamily: 'monospace', fontSize: '12px' }
              }}
              sx={{ mb: 2 }}
            />

            <Button
              variant="outlined"
              onClick={processPastedYaml}
              disabled={!pastedYaml.trim()}
              data-testid="yaml-paste-import"
            >
              Import from Pasted YAML
            </Button>
          </>
        )}

        {/* Step 2: Preview */}
        {step === 'preview' && importResult && (
          <>
            {/* Timeline metadata - editable */}
            <TextField
              autoFocus
              margin="dense"
              label="Title"
              fullWidth
              required
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              helperText={title.length < 3 ? 'Title must be at least 3 characters' : ''}
              error={title.length > 0 && title.length < 3}
              sx={{ mb: 2 }}
            />

            <TextField
              margin="dense"
              label="Description"
              fullWidth
              multiline
              rows={2}
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              sx={{ mb: 2 }}
            />

            <TextField
              margin="dense"
              label="Timeline ID"
              fullWidth
              required
              value={customId}
              onChange={(e) => {
                const newValue = e.target.value.toLowerCase();
                setCustomId(newValue);
                setIsIdManuallyEdited(newValue !== '' && newValue !== autoGeneratedSlug);
              }}
              onBlur={handleIdBlur}
              error={!!idError}
              helperText={idError || `URL: /${currentUser?.username || 'user'}/timeline/${customId || '...'}`}
              sx={{ mb: 2 }}
            />

            <FormControl fullWidth sx={{ mb: 2 }}>
              <InputLabel>Visibility</InputLabel>
              <Select
                value={visibility}
                label="Visibility"
                onChange={(e) => setVisibility(e.target.value as TimelineVisibility)}
              >
                <MenuItem value="public">Public - Visible to everyone</MenuItem>
                <MenuItem value="unlisted">Unlisted - Accessible via URL only</MenuItem>
                <MenuItem value="private">Private - Only you can see</MenuItem>
              </Select>
            </FormControl>

            <Divider sx={{ my: 2 }} />

            {/* Events preview */}
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 1 }}>
              <Typography variant="subtitle2">Events to Import</Typography>
              <Chip
                size="small"
                label={`${importResult.events.length} events`}
                color="primary"
                variant="outlined"
              />
            </Box>

            <Paper
              variant="outlined"
              sx={{ maxHeight: 200, overflow: 'auto', p: 1 }}
            >
              <List dense>
                {importResult.events.slice(0, 10).map((event, i) => (
                  <ListItem key={i} sx={{ py: 0.5 }}>
                    <ListItemText
                      primary={event.title}
                      secondary={`${event.date}${event.endDate ? ` - ${event.endDate}` : ''}${event.time ? ` at ${event.time}` : ''}`}
                      primaryTypographyProps={{ variant: 'body2', noWrap: true }}
                      secondaryTypographyProps={{ variant: 'caption' }}
                    />
                  </ListItem>
                ))}
                {importResult.events.length > 10 && (
                  <ListItem>
                    <ListItemText
                      secondary={`...and ${importResult.events.length - 10} more events`}
                      secondaryTypographyProps={{ variant: 'caption', fontStyle: 'italic' }}
                    />
                  </ListItem>
                )}
              </List>
            </Paper>
          </>
        )}

        {/* Step 3: Creating */}
        {step === 'creating' && (
          <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center', py: 4 }}>
            <CircularProgress sx={{ mb: 2 }} />
            <Typography>Creating timeline with {importResult?.events.length || 0} events...</Typography>
          </Box>
        )}
      </DialogContent>

      <DialogActions>
        {step === 'upload' && (
          <Button onClick={handleClose}>Cancel</Button>
        )}
        {step === 'preview' && (
          <>
            <Button onClick={handleBack}>Back</Button>
            <Button
              onClick={handleCreate}
              variant="contained"
              disabled={!isFormValid}
              data-testid="import-confirm-button"
            >
              Import Timeline
            </Button>
          </>
        )}
      </DialogActions>
    </Dialog>
  );
}
