"""
Agent Logger Module

Provides deterministic logging for agent spawns and results.
Updates IAC.md (Inter-Agent Communication) and CONTEXT.md automatically.

This module ensures all agent interactions are logged consistently,
without relying on agents to update documentation themselves.
"""

import uuid
from datetime import datetime
from pathlib import Path
from typing import Optional, Any
from dataclasses import dataclass


def get_agents_dir() -> Path:
    """Get the agents directory path."""
    return Path(__file__).parent


def generate_spawn_id() -> str:
    """Generate a short unique ID for a spawn."""
    return uuid.uuid4().hex[:8]


def now_iso() -> str:
    """Get current timestamp in ISO format."""
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def now_time() -> str:
    """Get current time only."""
    return datetime.now().strftime("%H:%M:%S")


def now_date() -> str:
    """Get current date only."""
    return datetime.now().strftime("%Y-%m-%d")


@dataclass
class SpawnRecord:
    """Record of an agent spawn for logging."""
    spawn_id: str
    agent: str
    model: str
    task_summary: str
    prompt: str
    tools: list[str]
    started_at: str
    completed_at: Optional[str] = None
    duration_seconds: Optional[float] = None
    success: Optional[bool] = None
    cost_usd: Optional[float] = None
    result_summary: Optional[str] = None
    error: Optional[str] = None


class AgentLogger:
    """
    Logger for agent spawns and results.

    Manages IAC.md and CONTEXT.md updates.
    """

    def __init__(self):
        self.agents_dir = get_agents_dir()
        self.iac_path = self.agents_dir / "IAC.md"
        self.context_path = self.agents_dir / "CONTEXT.md"
        self.active_spawns: dict[str, SpawnRecord] = {}
        self.max_recent_runs = 10

    def _ensure_iac_exists(self):
        """Ensure IAC.md exists with proper header."""
        if not self.iac_path.exists():
            self.iac_path.write_text(
                "# Inter-Agent Communication Log\n\n"
                "This file is auto-generated by the agent orchestration system.\n"
                "Do not edit manually.\n\n"
                "---\n\n",
                encoding='utf-8'
            )

    def _read_iac(self) -> str:
        """Read IAC.md content."""
        self._ensure_iac_exists()
        return self.iac_path.read_text(encoding='utf-8')

    def _append_iac(self, content: str):
        """Append content to IAC.md."""
        self._ensure_iac_exists()
        current = self._read_iac()

        # Check if we need a new date header
        today = now_date()
        if f"## {today}" not in current:
            content = f"## {today}\n\n{content}"

        with open(self.iac_path, 'a', encoding='utf-8') as f:
            f.write(content)

    def log_spawn_start(
        self,
        agent: str,
        model: str,
        prompt: str,
        tools: list[str],
        task_summary: Optional[str] = None,
    ) -> str:
        """
        Log the start of an agent spawn.

        Returns the spawn_id for tracking.
        """
        spawn_id = generate_spawn_id()
        started_at = now_iso()

        # Create task summary from first line of prompt if not provided
        if not task_summary:
            first_line = prompt.split('\n')[0][:80]
            task_summary = first_line + ('...' if len(prompt.split('\n')[0]) > 80 else '')

        record = SpawnRecord(
            spawn_id=spawn_id,
            agent=agent,
            model=model,
            task_summary=task_summary,
            prompt=prompt,
            tools=tools,
            started_at=started_at,
        )
        self.active_spawns[spawn_id] = record

        # Write to IAC.md
        tools_str = ', '.join(tools) if tools else 'None'
        prompt_preview = prompt[:500] + ('...' if len(prompt) > 500 else '')

        iac_entry = f"""
### [{now_time()}] Spawn #{spawn_id} - STARTED
- **Agent:** {agent} ({model})
- **Task:** {task_summary}
- **Tools:** {tools_str}
- **Prompt Preview:**
```
{prompt_preview}
```
- **Status:** Running...

"""
        self._append_iac(iac_entry)

        # Update CONTEXT.md with active spawn
        self._update_context()

        return spawn_id

    def log_spawn_complete(
        self,
        spawn_id: str,
        success: bool,
        result_text: str,
        duration_seconds: float,
        cost_usd: float = 0.0,
        error: Optional[str] = None,
    ):
        """Log the completion of an agent spawn."""
        record = self.active_spawns.get(spawn_id)
        if not record:
            # Spawn wasn't tracked, create minimal record
            record = SpawnRecord(
                spawn_id=spawn_id,
                agent="unknown",
                model="unknown",
                task_summary="Unknown task",
                prompt="",
                tools=[],
                started_at=now_iso(),
            )

        record.completed_at = now_iso()
        record.duration_seconds = duration_seconds
        record.success = success
        record.cost_usd = cost_usd
        record.error = error

        # Create result summary (first 200 chars)
        result_summary = result_text[:200] + ('...' if len(result_text) > 200 else '')
        record.result_summary = result_summary

        # Write completion to IAC.md
        status = "SUCCESS" if success else f"FAILED: {error or 'Unknown error'}"
        iac_entry = f"""
### [{now_time()}] Spawn #{spawn_id} - COMPLETED
- **Status:** {status}
- **Duration:** {duration_seconds:.1f}s
- **Cost:** ${cost_usd:.4f}
- **Result Summary:** {result_summary}

---

"""
        self._append_iac(iac_entry)

        # Remove from active spawns
        if spawn_id in self.active_spawns:
            del self.active_spawns[spawn_id]

        # Update CONTEXT.md
        self._update_context(completed_record=record)

    def _update_context(self, completed_record: Optional[SpawnRecord] = None):
        """Update CONTEXT.md with current state."""
        # Load existing recent runs
        recent_runs = self._load_recent_runs()

        # Add completed record to recent runs
        if completed_record:
            recent_runs.insert(0, {
                'time': completed_record.completed_at or now_iso(),
                'agent': f"{completed_record.agent} ({completed_record.model})",
                'task': completed_record.task_summary,
                'duration': f"{completed_record.duration_seconds:.1f}s" if completed_record.duration_seconds else "N/A",
                'result': "Success" if completed_record.success else f"Failed: {completed_record.error or 'Unknown'}",
            })
            recent_runs = recent_runs[:self.max_recent_runs]

        # Build active agents table
        active_table = "| ID | Agent | Task | Started |\n|-----|-------|------|--------|\n"
        if self.active_spawns:
            for sid, rec in self.active_spawns.items():
                active_table += f"| {sid} | {rec.agent} | {rec.task_summary[:40]} | {rec.started_at} |\n"
        else:
            active_table += "| - | - | No active agents | - |\n"

        # Build recent runs table
        recent_table = "| Time | Agent | Task | Duration | Result |\n|------|-------|------|----------|--------|\n"
        for run in recent_runs:
            recent_table += f"| {run['time']} | {run['agent']} | {run['task'][:30]} | {run['duration']} | {run['result'][:20]} |\n"
        if not recent_runs:
            recent_table += "| - | - | No recent runs | - | - |\n"

        # Write CONTEXT.md
        context_content = f"""# Agent Context

> Auto-generated by agents/logger.py. Do not edit manually.

**Last Updated:** {now_iso()} UTC

---

## Active Agents

{active_table}

---

## Recent Runs (Last {self.max_recent_runs})

{recent_table}

---

## Notes

- This file is overwritten on each agent spawn/completion
- See IAC.md for full interaction logs
- See DESIGN.md for architecture documentation
"""
        self.context_path.write_text(context_content, encoding='utf-8')

        # Save recent runs for persistence
        self._save_recent_runs(recent_runs)

    def _load_recent_runs(self) -> list[dict]:
        """Load recent runs from a simple cache file."""
        cache_path = self.agents_dir / ".recent_runs.json"
        if cache_path.exists():
            import json
            try:
                return json.loads(cache_path.read_text(encoding='utf-8'))
            except:
                return []
        return []

    def _save_recent_runs(self, runs: list[dict]):
        """Save recent runs to a simple cache file."""
        import json
        cache_path = self.agents_dir / ".recent_runs.json"
        cache_path.write_text(json.dumps(runs, indent=2), encoding='utf-8')


# Global logger instance
_logger: Optional[AgentLogger] = None


def get_logger() -> AgentLogger:
    """Get or create the global logger instance."""
    global _logger
    if _logger is None:
        _logger = AgentLogger()
    return _logger


def log_spawn_start(
    agent: str,
    model: str,
    prompt: str,
    tools: list[str],
    task_summary: Optional[str] = None,
) -> str:
    """Log the start of an agent spawn. Returns spawn_id."""
    return get_logger().log_spawn_start(agent, model, prompt, tools, task_summary)


def log_spawn_complete(
    spawn_id: str,
    success: bool,
    result_text: str,
    duration_seconds: float,
    cost_usd: float = 0.0,
    error: Optional[str] = None,
):
    """Log the completion of an agent spawn."""
    get_logger().log_spawn_complete(
        spawn_id, success, result_text, duration_seconds, cost_usd, error
    )
